/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east2",
    "aws_appsync_graphqlEndpoint": process.env.APPSYNC_GRAPHQL_ENDPOINT,
    "aws_appsync_region": "us-east2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": process.env.APPSYNC_GRAPHQL_API_KEY,
    Auth: {
        region: "eu-west-2",
        userPoolId: "eu-west-2_WCd5yGK2n",
        userPoolWebClientId: "5gj3nud6r9p6vbns39cckisdpu",
    },
};


export default awsmobile;