
name: CI on dev

on:
  push:
    branches: [ newDev ]

  workflow_dispatch:

jobs:

  Website:
    runs-on: ubuntu-latest
    env:
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }} 
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }} 
      COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }} 
      COGNITO_USER_POOL_CLIENT_ID: ${{ secrets.COGNITO_USER_POOL_CLIENT_ID }} 
      APPSYNC_GRAPHQL_API_KEY: ${{ secrets.APPSYNC_GRAPHQL_API_KEY }} 
      APPSYNC_GRAPHQL_ENDPOINT: ${{ secrets.APPSYNC_GRAPHQL_ENDPOINT }} 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: ls
        run: ls
        env: 
          GATSBY_SPACE_ID: ${{ secrets.GATSBY_SPACE_ID }} 
          GATSBY_ACCESS_TOKEN: ${{ secrets.GATSBY_ACCESS_TOKEN }} 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: eu-west-2
      - name: Installing Nodejs
        uses: actions/setup-node@v2-beta
        with:
           node-version: '12'
      - name: Installing AWS-CDK
        run: npm install -g aws-cdk@1.87.1

      - name: Installing Gatsby
        run: yarn global add gatsby-cli

      - name: Installing Frontend dependencies and run test
        run: cd new_website && yarn install && cd cdk && npm install 
      #  && cd .. && npm run test
      - name : build Frontend
        run : cd new_website && npm run build && cd cdk && npm run build && cdk deploy --require-approval never
# made change
