/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": process.env.APPSYNC_GRAPHQL_ENDPOINT,
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": process.env.APPSYNC_GRAPHQL_API_KEY,
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_9D0XTY3eH",
        "userPoolWebClientId": "28qp4pb6g5sqmgiupae8jt0gdf"
    }
};


export default awsmobile;

