projects:
  tenantOnboarding:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-west-2
        apiId: nxzgc6rhn5emhoqj4ddovgkf7a
        maxDepth: 2
extensions:
  amplify:
    version: 3
