type Query {
    todos: [Todo]
  }
  type Todo {
    id: ID!
    description: String!
  }
input TodoInput {
    id: ID!
    description: String!
  }

  type Mutation {
    addTodo(todo: TodoInput!): Todo
    deleteTodo(id: String!): String
  }